version: 0.0
os: linux
files:
    - source: /
      destination: /revision
permissions:
    - object: /var/www
      owner: ec2-user
      group: ec2-user
hooks:
    AfterInstall:
        - location: update-app.sh
          timeout: 10
          runas: ec2-user
    ApplicationStart:
        - location: restart-app.sh
          timeout: 10
          runas: ec2-user
